services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import

volumes:
  postgres_data: